### ISSUE TITLE
[1.10.2] Gift of the Gods - Unlimited use

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [sokratis12GR/ArmorPlus#109]
**ArmorPlus Version**: armorplus-1.10.2-8.5.1.2

**TheDragonLib Version**: thedragonlib-1.10.2-1.0.3.1

**MinecraftForge Version**: 1.10.2-forge1.10.2-12.18.3.2234

**Minecraft Version**: 1.10.2

The Gift of the Gods has unlimited uses, even though the tool tip says max use 1. I've used it about 20 times now. It has however a cool-down. If that's intended, then the cooldown needs to be much, much longer. Like 5 min or so. Or via config file.

SSP

**Comment by sokratis12GR** [comment]
SSP / SMP ?

**Comment by sokratis12GR** [comment]
Fixed in [armorplus-1.10.2-8.5.2.3](https://minecraft.curseforge.com/projects/armorplus/files/2385714)

**Comment by Unrepentant-Atheist** [comment]
armorplus-1.10.2-8.5.2.3.jar didn't fix that bug, just tested. Maybe because I have the "old" GotG?

Old and new GotG, still have unlimited uses.

**Comment by sokratis12GR** [comment]
Alright, could you try some of the following things and let me know if it worked:

* Delete the config file `configs/armorplus.cfg`
* Create a new separate world

Also:
Where does it happen?
* [ ] Single player
* [ ] Multiplayer

**Comment by Unrepentant-Atheist** [comment]
Deleted my whole config folder. I just ran with this: http://imgur.com/a/OVzYG

And still unlimited uses.  https://imgur.com/a/4xDsG

Singleplayer.

**Comment by sokratis12GR** [comment]
@Unrepentant-Atheist in the screenshot it shows it has 0 durability = 1 more use
The item it self has 2 uses by default, cooldown length can be changed via the config, same with amount of uses.
Let me know if using the second time destroys the item.

**Comment by sokratis12GR** [comment]
Closing this issue until more evidence is provided. Please, if you could make a short video on it It would help a lot.
