### ISSUE TITLE
[1.11.2] ArmorPlus Bows crash

### ISSUE THREAD

**Issue by MakroxMiau** [sokratis12GR/ArmorPlus#90]
**ArmorPlus Version**: armorplus-1.11.2-9.4.1.2-beta

**TheDragonLib Version**: thedragonlib-1.11.2-2.1.0

**MinecraftForge Version**: forge-1.11.2-13.20.0.2216

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://pastebin.com/UMRNe1tf

**What happens / happened?**: "Shutting Down Internal Server" and Crash

**How can I reproduce it?**: Craft a Lava Bow or get it with creative and shoot.

**(Optional) Mod List**: Minecraft Forge; Backpacks!; Potion Core Coremod; Mercurius Updater;
                                     Deadly Monsters; Advance Shulker Box; Armor Damage Recalc; TheDragonLib;
                                     ArmorPlus; Battle Towers; Better Achievements; Better PvP; EXCore;
                                     Just Enough Items; Forever Enough Items; Waila (Hwyla); Infernal Mobs;
                                     Inventory Tweaks; Iron Chest; JourneyMap; Level Up!; Lucky Block;
                                     MineColonies; OreExcavation; Potion Core; RebornCore;
                                     RebornCore-MCMultiPart; Simple Teleporters; Simulated Nights; Supply Drop
                                     (Added after the problem); TeleToro; ToroHealth Damage Indicators; 
                                     Waila Harvestability.

**PD**: If this is not a problem, it is surely my computer's fault.

**Comment by sokratis12GR** [comment]
I can confirm this as a bug, I'll fix it soon. for now please don't use any of the bows in 1.11.2, they are all broken

**Comment by MakroxMiau** [comment]
Nooo, I throw my old Bow to my dump of fire .c

**Comment by sokratis12GR** [comment]
there is no need of deleting it if you have it, just try to avoid using it until its fixed ;)

**Comment by MakroxMiau** [comment]
the minecraft bow, no the lava bow :c

**Comment by sokratis12GR** [comment]
Fixed on latest update, thanks for the report

**Comment by sokratis12GR** [comment]
Welp, I still haven't released the latest version... It will be out in some hours of some days

**Comment by sokratis12GR** [comment]
Fixed on latest

**Comment by MakroxMiau** [comment]
[Bug Bow](https://vimeo.com/202599426)
maan, I still have the problem 

Pd: The password of the video is Bow

**Comment by sokratis12GR** [comment]
Could you try in creative again while having an arrow in your inventory? If that also doesn't work I will need to fix gamemode 1 bows

**Comment by sokratis12GR** [comment]
This issue is hopefully fixed in the [armorplus-1.11.2-9.5.5.6-beta](https://minecraft.curseforge.com/projects/armorplus/files/2378145) version.

**Comment by MakroxMiau** [comment]
Oh, that's why in survival I was doing well just the lava bow.

PD: Google translate xd
